# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GDCorner
email: philip@gdcorner.com
author: "Philip Edwards"
description: >- # this means to ignore newlines until "baseurl:"
  Development beyond code
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gdcorner.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: boristsr
github_username:  boristsr

# Build settings
markdown: kramdown
theme: bulma-clean-theme
theme_color: '#3b3b3b'
#remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-sitemap

fixed_navbar: top

github:
  is_project_page: false

excerpt_separator: <!--more-->
show_excerpts: true

paginate: 5
paginate_path: "/articles/page:num"

post_assets_url: "/"

commento:
    enabled: true

navbar_logo: "/assets/images/logo-w-text-small.png"
hero_logo: "/assets/images/logo-large.png"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      hero_height: is-fullwidth
      show_sidebar: true
      image: /assets/images/default-social-card.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Philip Edwards"
      layout: post
      hero_height: is-fullwidth
      image: /assets/images/default-social-card.png
      show_sidebar: false
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      image: /assets/images/default-social-card.png
      layout: project
      hero_height: is-fullwidth
      show_sidebar: true
  - scope:
      path: ""
      type: "documentation"
    values:
      image: /assets/images/default-social-card.png
      layout: documentation
      hero_height: is-fullwidth
      show_sidebar: false
  - scope:
      path: "_documentation/wheelman"
    values:
      product: wheelman
  - scope:
      path: ""
      type: "products"
    values:
      image: /assets/images/default-social-card.png
      layout: product
      hero_height: is-fullwidth
      show_sidebar: false
      free_download: false
    

collections:
  projects: 
    output: true
  products: 
    output: true
  documentation: 
    output: true
  redirects: 
    output: true
    

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build/
  - Jenkinsfile
  - .gitignore
